<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="ImportInOperation"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples/d1/ImportInOperation"
                  targetNamespace="http://mrasoft.pl/mridl/examples/d1/ImportInOperation">
    <wsdl:import namespace="http://mrasoft.pl/mridl/examples/d1/ImportInOperation" location="ImportInOperation.wsdl"/>
    <wsdl:binding name="ImportInOperationSOAPBinding" type="tns:ImportInOperation">
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="op1">
			<soap:operation style="document"/>
			<wsdl:input name="op1">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="op1Response">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ImportInOperationService">
	     <wsdl:port name="ImportInOperation" binding="tns:ImportInOperationSOAPBinding">
	         <soap:address location="http://localhost/ImportInOperation"/>
	     </wsdl:port>
	 </wsdl:service>
</wsdl:definitions>
