/*
 * generated by Xtext
 */
package pl.mrasoft.mridl.ui.contentassist

import pl.mrasoft.mridl.ui.contentassist.AbstractMridlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MridlProposalProvider extends AbstractMridlProposalProvider {
}
