/*
 * generated by Xtext
 */
package pl.mrasoft.mridl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MridlUiModule extends pl.mrasoft.mridl.ui.AbstractMridlUiModule {
	public MridlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
