/*
 * generated by Xtext
 */
package pl.mrasoft.mridl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MridlRuntimeModule extends pl.mrasoft.mridl.AbstractMridlRuntimeModule {

}
