/*
* generated by Xtext
*/
package pl.mrasoft.mridl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MridlStandaloneSetup extends MridlStandaloneSetupGenerated{

	public static void doSetup() {
		new MridlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

