<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="HelloOperationComplexTypeParam"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples"
                  targetNamespace="http://mrasoft.pl/mridl/examples">		
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://mrasoft.pl/mridl/examples" schemaLocation="HelloOperationComplexTypeParam.xsd"/>
        </schema>
    </wsdl:types>
	<wsdl:message name="op1">
		<wsdl:part element="tns:op1" name="parameters"/>
	</wsdl:message>	
	<wsdl:message name="op1Response">
		<wsdl:part element="tns:op1Response" name="parameters"/>
	</wsdl:message>		    
	<wsdl:portType name="HelloOperationComplexTypeParam">
		<wsdl:operation name="op1">
			<wsdl:input message="tns:op1" name="op1"/>
			<wsdl:output message="tns:op1Response" name="op1Response"/>
		</wsdl:operation>		    
	</wsdl:portType>
</wsdl:definitions>
