<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="FaultDocumentation"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples/d1/FaultDocumentation"
                  targetNamespace="http://mrasoft.pl/mridl/examples/d1/FaultDocumentation">
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://mrasoft.pl/mridl/examples/d1/FaultDocumentation" schemaLocation="FaultDocumentation.xsd"/>
        </schema>
    </wsdl:types>
	<wsdl:message name="op1">
		<wsdl:part element="tns:op1" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="TestFault2Exception">
		<wsdl:part name="TestFault2Exception" element="tns:TestFault2"/>
	</wsdl:message>
	<wsdl:portType name="FaultDocumentation">
		<wsdl:operation name="op1">
			<wsdl:input message="tns:op1" name="op1"/>
			<wsdl:fault name="TestFault2Exception" message="tns:TestFault2Exception">
				<wsdl:documentation>
					fault doc
				</wsdl:documentation>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
