<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="OperationDocumentation"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples/d1/OperationDocumentation"
                  targetNamespace="http://mrasoft.pl/mridl/examples/d1/OperationDocumentation">
	<wsdl:import namespace="http://mrasoft.pl/mridl/examples/d1/OperationDocumentation" location="OperationDocumentation.wsdl"/>
	<wsdl:binding name="OperationDocumentationSOAPBinding" type="tns:OperationDocumentation">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="op1">
			<soap:operation style="document"/>
			<wsdl:input name="op1">
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OperationDocumentationService">
		<wsdl:port name="OperationDocumentation" binding="tns:OperationDocumentationSOAPBinding">
			<soap:address location="http://localhost/OperationDocumentation"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
