<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="SameFaultInManyOperations"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples/d1/SameFaultInManyOperations"
                  targetNamespace="http://mrasoft.pl/mridl/examples/d1/SameFaultInManyOperations">
    <wsdl:import namespace="http://mrasoft.pl/mridl/examples/d1/SameFaultInManyOperations" location="SameFaultInManyOperations.wsdl"/>
    <wsdl:binding name="SameFaultInManyOperationsSOAPBinding" type="tns:SameFaultInManyOperations">
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="op1">
			<soap:operation style="document"/>
			<wsdl:input name="op1">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="op1Response">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="TestFaultException">
				<soap:fault name="TestFaultException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="op2">
			<soap:operation style="document"/>
			<wsdl:input name="op2">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="op2Response">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="TestFaultException">
				<soap:fault name="TestFaultException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SameFaultInManyOperationsService">
	     <wsdl:port name="SameFaultInManyOperations" binding="tns:SameFaultInManyOperationsSOAPBinding">
	         <soap:address location="http://localhost/SameFaultInManyOperations"/>
	     </wsdl:port>
	 </wsdl:service>
</wsdl:definitions>
