<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="HelloParameterLess"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples"
                  targetNamespace="http://mrasoft.pl/mridl/examples">
    <wsdl:import namespace="http://mrasoft.pl/mridl/examples" location="HelloParameterLess.wsdl"/>
    <wsdl:binding name="HelloParameterLessSOAPBinding" type="tns:HelloParameterLess">
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="sayHello">
			<soap:operation style="document"/>
			<wsdl:input name="sayHello">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="sayHelloResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="HelloParameterLessService">
	     <wsdl:port name="HelloParameterLess" binding="tns:HelloParameterLessSOAPBinding">
	         <soap:address location="http://localhost/HelloParameterLess"/>
	     </wsdl:port>
	 </wsdl:service>
</wsdl:definitions>
