<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="Hello"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples"
                  targetNamespace="http://mrasoft.pl/mridl/examples">
    <wsdl:import namespace="http://mrasoft.pl/mridl/examples" location="Hello.wsdl"/>
    <wsdl:binding name="HelloSOAPBinding" type="tns:Hello">
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="sayHello2">
			<soap:operation style="document"/>
			<wsdl:input name="sayHello2">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="sayHello2Response">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="HelloService">
	     <wsdl:port name="Hello" binding="tns:HelloSOAPBinding">
	         <soap:address location="http://localhost/Hello"/>
	     </wsdl:port>
	 </wsdl:service>
</wsdl:definitions>
