<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="VoidOperation"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://mrasoft.pl/mridl/examples/hello/VoidOperation"
                  targetNamespace="http://mrasoft.pl/mridl/examples/hello/VoidOperation">
    <wsdl:import namespace="http://mrasoft.pl/mridl/examples/hello/VoidOperation" location="VoidOperation.wsdl"/>
    <wsdl:binding name="VoidOperationSOAPBinding" type="tns:VoidOperation">
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="op1">
			<soap:operation style="document"/>
			<wsdl:input name="op1">
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="VoidOperationService">
	     <wsdl:port name="VoidOperation" binding="tns:VoidOperationSOAPBinding">
	         <soap:address location="http://localhost/VoidOperation"/>
	     </wsdl:port>
	 </wsdl:service>
</wsdl:definitions>
